/**
 * @file adc_emif.h
 * @brief ADC EMIF接口配置文件
 * @details 定义ADC的EMIF接口相关引脚和函数，负责ADC的EMIF接口配置。
 * @ingroup ADC_EMIF
 */

#ifndef _ADC_EMIF_H_
#define _ADC_EMIF_H_

/**
 * @defgroup ADC_EMIF ADC EMIF控制
 * @ingroup ADC_API
 * @brief ADC EMIF控制模块
 * @details 
 * 定义ADC的EMIF接口相关引脚和函数，负责CPU的EMIF接口配置。
 * 
 * 主要职责包括：
 * - 定义ADC相关的EMIF引脚宏
 * - 实现EMIF接口的初始化
 * 
 * 本模块为ADC驱动提供EMIF接口支持，实现ADC数据的读取功能。
 * @{
 */


/// @cond INTERNAL_MACROS
/**
 * @brief 引脚定义
 */
/*EMIF引脚定义*/
//ADC_RDCS EMFA_CSn2 GPIO3[15]
#define ADC_RDCS_MASK           SYSCFG_PINMUX7_PINMUX7_3_0
#define ADC_RDCS_ENABLE         (SYSCFG_PINMUX7_PINMUX7_3_0_NEMA_CS2 << SYSCFG_PINMUX7_PINMUX7_3_0_SHIFT)
//ADC_DATA EMFA_DATA
#define ADC_DATA0_MASK          SYSCFG_PINMUX9_PINMUX9_31_28
#define ADC_DATA0_ENABLE        (SYSCFG_PINMUX9_PINMUX9_31_28_EMA_D0 << SYSCFG_PINMUX9_PINMUX9_31_28_SHIFT)
#define ADC_DATA1_MASK          SYSCFG_PINMUX9_PINMUX9_27_24
#define ADC_DATA1_ENABLE        (SYSCFG_PINMUX9_PINMUX9_27_24_EMA_D1 << SYSCFG_PINMUX9_PINMUX9_27_24_SHIFT)
#define ADC_DATA2_MASK          SYSCFG_PINMUX9_PINMUX9_23_20
#define ADC_DATA2_ENABLE        (SYSCFG_PINMUX9_PINMUX9_23_20_EMA_D2 << SYSCFG_PINMUX9_PINMUX9_23_20_SHIFT)
#define ADC_DATA3_MASK          SYSCFG_PINMUX9_PINMUX9_19_16
#define ADC_DATA3_ENABLE        (SYSCFG_PINMUX9_PINMUX9_19_16_EMA_D3 << SYSCFG_PINMUX9_PINMUX9_19_16_SHIFT)
#define ADC_DATA4_MASK          SYSCFG_PINMUX9_PINMUX9_15_12
#define ADC_DATA4_ENABLE        (SYSCFG_PINMUX9_PINMUX9_15_12_EMA_D4 << SYSCFG_PINMUX9_PINMUX9_15_12_SHIFT)
#define ADC_DATA5_MASK          SYSCFG_PINMUX9_PINMUX9_11_8
#define ADC_DATA5_ENABLE        (SYSCFG_PINMUX9_PINMUX9_11_8_EMA_D5 << SYSCFG_PINMUX9_PINMUX9_11_8_SHIFT)
#define ADC_DATA6_MASK          SYSCFG_PINMUX9_PINMUX9_7_4
#define ADC_DATA6_ENABLE        (SYSCFG_PINMUX9_PINMUX9_7_4_EMA_D6 << SYSCFG_PINMUX9_PINMUX9_7_4_SHIFT)
#define ADC_DATA7_MASK          SYSCFG_PINMUX9_PINMUX9_3_0
#define ADC_DATA7_ENABLE        (SYSCFG_PINMUX9_PINMUX9_3_0_EMA_D7 << SYSCFG_PINMUX9_PINMUX9_3_0_SHIFT)
#define ADC_DATA8_MASK          SYSCFG_PINMUX8_PINMUX8_31_28
#define ADC_DATA8_ENABLE        (SYSCFG_PINMUX8_PINMUX8_31_28_EMA_D8 << SYSCFG_PINMUX8_PINMUX8_31_28_SHIFT)
#define ADC_DATA9_MASK          SYSCFG_PINMUX8_PINMUX8_27_24
#define ADC_DATA9_ENABLE        (SYSCFG_PINMUX8_PINMUX8_27_24_EMA_D9 << SYSCFG_PINMUX8_PINMUX8_27_24_SHIFT)
#define ADC_DATA10_MASK         SYSCFG_PINMUX8_PINMUX8_23_20
#define ADC_DATA10_ENABLE       (SYSCFG_PINMUX8_PINMUX8_23_20_EMA_D10 << SYSCFG_PINMUX8_PINMUX8_23_20_SHIFT)
#define ADC_DATA11_MASK         SYSCFG_PINMUX8_PINMUX8_19_16
#define ADC_DATA11_ENABLE       (SYSCFG_PINMUX8_PINMUX8_19_16_EMA_D11 << SYSCFG_PINMUX8_PINMUX8_19_16_SHIFT)
#define ADC_DATA12_MASK         SYSCFG_PINMUX8_PINMUX8_15_12
#define ADC_DATA12_ENABLE       (SYSCFG_PINMUX8_PINMUX8_15_12_EMA_D12 << SYSCFG_PINMUX8_PINMUX8_15_12_SHIFT)
#define ADC_DATA13_MASK         SYSCFG_PINMUX8_PINMUX8_11_8
#define ADC_DATA13_ENABLE       (SYSCFG_PINMUX8_PINMUX8_11_8_EMA_D13 << SYSCFG_PINMUX8_PINMUX8_11_8_SHIFT)
#define ADC_DATA14_MASK         SYSCFG_PINMUX8_PINMUX8_7_4
#define ADC_DATA14_ENABLE       (SYSCFG_PINMUX8_PINMUX8_7_4_EMA_D14 << SYSCFG_PINMUX8_PINMUX8_7_4_SHIFT)
#define ADC_DATA15_MASK         SYSCFG_PINMUX8_PINMUX8_3_0
#define ADC_DATA15_ENABLE       (SYSCFG_PINMUX8_PINMUX8_3_0_EMA_D15 << SYSCFG_PINMUX8_PINMUX8_3_0_SHIFT)

/// @endcond



/**
 * @brief ADC EMIF接口初始化函数
 * @details 初始化ADC的EMIF接口，配置引脚和参数。
 */
void Adc_Emif_Init(void);

/** @} */

#endif /* _ADC_EMIF_H_ */
