/**
 * @file led_pin.h
 * @brief LED引脚配置文件
 * @details 定义LED相关的引脚宏和底层引脚控制函数。
 * @ingroup LED_PIN
 */

#ifndef _LED_PIN_H_
#define _LED_PIN_H_

/**
 * @defgroup LED_PIN LED引脚控制
 * @ingroup LED_API
 * @brief LED引脚控制模块
 * @details 
 * 定义LED相关的引脚宏和底层引脚控制函数。
 * 
 * 主要职责包括：
 * - 定义LED相关的引脚宏，包括引脚编号、掩码和使能值
 * - 负责LED引脚的初始化，包括PSC初始化、引脚复用配置和GPIO方向设置
 * - 提供LED引脚状态设置函数，支持点亮、关闭和翻转操作
 * - 直接操作硬件寄存器，实现底层的GPIO控制
 * 
 * 本模块为上层驱动提供硬件支持，是整个LED驱动的基础。
 * @{
 */

/// @cond INTERNAL_MACROS
/* 按键引脚定义 */
#define LED1_BLUE_PIN 6
#define LED1_BLUE_MASK SYSCFG_PINMUX1_PINMUX1_11_8
#define LED1_BLUE_ENABLE (SYSCFG_PINMUX1_PINMUX1_11_8_GPIO0_5 << SYSCFG_PINMUX1_PINMUX1_11_8_SHIFT)
#define LED1_RED_PIN 7
#define LED1_RED_MASK SYSCFG_PINMUX1_PINMUX1_7_4
#define LED1_RED_ENABLE (SYSCFG_PINMUX1_PINMUX1_7_4_GPIO0_6 << SYSCFG_PINMUX1_PINMUX1_7_4_SHIFT)
#define LED2_BLUE_PIN 9
#define LED2_BLUE_MASK SYSCFG_PINMUX0_PINMUX0_31_28
#define LED2_BLUE_ENABLE (SYSCFG_PINMUX0_PINMUX0_31_28_GPIO0_8 << SYSCFG_PINMUX0_PINMUX0_31_28_SHIFT)
#define LED2_RED_PIN 10
#define LED2_RED_MASK SYSCFG_PINMUX0_PINMUX0_27_24
#define LED2_RED_ENABLE (SYSCFG_PINMUX0_PINMUX0_27_24_GPIO0_9 << SYSCFG_PINMUX0_PINMUX0_27_24_SHIFT)
#define LED3_BLUE_PIN 11
#define LED3_BLUE_MASK SYSCFG_PINMUX0_PINMUX0_23_20
#define LED3_BLUE_ENABLE (SYSCFG_PINMUX0_PINMUX0_23_20_GPIO0_10 << SYSCFG_PINMUX0_PINMUX0_23_20_SHIFT)
#define LED3_RED_PIN 12
#define LED3_RED_MASK SYSCFG_PINMUX0_PINMUX0_19_16
#define LED3_RED_ENABLE (SYSCFG_PINMUX0_PINMUX0_19_16_GPIO0_11 << SYSCFG_PINMUX0_PINMUX0_19_16_SHIFT)
#define LED4_BLUE_PIN 14
#define LED4_BLUE_MASK SYSCFG_PINMUX0_PINMUX0_11_8
#define LED4_BLUE_ENABLE (SYSCFG_PINMUX0_PINMUX0_11_8_GPIO0_13 << SYSCFG_PINMUX0_PINMUX0_11_8_SHIFT)
#define LED4_RED_PIN 16
#define LED4_RED_MASK SYSCFG_PINMUX0_PINMUX0_3_0
#define LED4_RED_ENABLE (SYSCFG_PINMUX0_PINMUX0_3_0_GPIO0_15 << SYSCFG_PINMUX0_PINMUX0_3_0_SHIFT)
#define LED1_CORE_PIN 109
#define LED1_CORE_MASK SYSCFG_PINMUX13_PINMUX13_15_12
#define LED1_CORE_ENABLE (SYSCFG_PINMUX13_PINMUX13_15_12_GPIO6_12 << SYSCFG_PINMUX13_PINMUX13_15_12_SHIFT)
#define LED2_CORE_PIN 110
#define LED2_CORE_MASK SYSCFG_PINMUX13_PINMUX13_11_8
#define LED2_CORE_ENABLE (SYSCFG_PINMUX13_PINMUX13_11_8_GPIO6_13 << SYSCFG_PINMUX13_PINMUX13_11_8_SHIFT)
// 控制LED灯亮灭状态
#define LED_STA_ON 1
#define LED_STA_OFF 2
#define LED_STA_TOGGLE 3
/// @endcond /* INTERNAL_MACROS 结束 */


/**
 * @brief 初始化LED引脚
 * @details 配置LED相关的GPIO引脚，设置为输出模式
 */
void LED_PinInit(void);

/**
 * @brief 设置LED引脚状态
 * @details 根据指定的状态控制LED引脚
 * @param pinNumber 引脚编号
 * @param bitState 状态(LED_STA_ON / LED_STA_OFF / LED_STA_TOGGLE)
 */
void LED_PinSet(unsigned int pinNumber, unsigned int bitState);

/** @} */

#endif /* _LED_PIN_H_ */
