

/* This file contains the PRU instructions in a C array which are to  */
/* be downloaded from the host CPU to the PRU instruction memory.     */
/* This file is generated by the PRU assembler.                       */



const unsigned int PRU1_Code[] =  
{
    0x00000000,
    0x2300059e,
    0x2300159e,
    0x7f0000fe,
    0x2a000000,
    0x2401c8e0,
    0x0501e0e0,
    0x6f00e0ff,
    0x240000ee,
    0x240000ef,
    0x24c6ffce,
    0x24fff28e,
    0xf1000e0f,
    0x5700eff8,
    0x2401c2c3,
    0x24104683,
    0xf1000302,
    0x1102e2e2,
    0x5700e2f3,
    0xe1000302,
    0x209e0000,
    0x2401e2c5,
    0x24606c85,
    0x242000c4,
    0x24000084,
    0xe1002584,
    0x240072e0,
    0x0501e0e0,
    0x6f00e0ff,
    0x2401e2c5,
    0x24606885,
    0x242000c4,
    0x24000084,
    0xe1002584,
    0x209e0000,
    0x240474e0,
    0x0501e0e0,
    0x6f00e0ff,
    0x209e0000
};

